# This is a basic workflow to help you get started with Actions

name: WhereWulff-test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  WhereWulff:
    # The type of runner that the job will run on
    runs-on:
     - self-hosted
     - linux
     - workspace-atomate
    container:
      image: ulissigroup/kubeflow_vasp:atomate_stack
      volumes: 
      - /home/jovyan/workspace-atomate:/home/jovyan/workspace-atomate
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # 1) Authenticate to laikapack
      - uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.ZULISSI_KUBECONFIG }}
          context: ulissigroup-desktops-fqdn
        id: setcontext
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout the repo
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: ls -al

